version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable
    executor: node/14.x
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          node-version: '14.17'
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  install_deps:
    jobs:
      - build_and_test
